import{mkdir,readFile,writeFile}from"node:fs/promises";
const key=process.env.NVE_API_KEY;if(!key)throw Error("Missing NVE_API_KEY");const now=new Date(),year=now.getFullYear(),cutoff=new Date(now-7*864e5),today=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Oslo",year:"numeric",month:"2-digit",day:"2-digit"}).format(now);
async function get(url,opt={}){const r=await fetch(url,opt);if(!r.ok)throw Error(`${r.status} ${url}`);return r.json()}
const headers={"content-type":"application/json",accept:"application/json","X-SetLanguage":"nb"};
async function beatId(name){const j=await get("https://api.elveguiden.no/api/v1/river/laksebors/25",{headers:{accept:"application/json","X-SetLanguage":"nb"}});return j.data?.beats?.find(x=>x.name===name)?.id}
async function catches(beatId,beatName){if(!beatId)return[];let out=[];for(let page=1;page<=10;page++){const body={page,beat_id:beatId,river_id:25,year,orderBy:"date",order:"desc",equipment_filter:[],fish_type_filter:[],catch_release_filter:[],boat_filter:[]};const j=await get("https://api.elveguiden.no/api/v2/catches/latest-catches",{method:"POST",headers,body:JSON.stringify(body)}),p=j?.data?.catches||j?.data,rows=p?.data||[];for(const c of rows){const dt=new Date(`${c.date}T${c.time_of_day||"12:00"}:00+02:00`);out.push({id:c.id,date:c.date,dateTime:dt.toISOString(),species:c.fish_type?.name_no||c.fish_type?.name||"–",weight:+c.weight||0,method:c.equipment?.name_no||c.equipment?.name||c.equipment?.slug||"–",beat:c.beat?.name||beatName})}if(!rows.length||rows.some(c=>c.date<today)||page>=(p?.last_page||1))break}return out}
async function nve(){const j=await get("https://hydapi.nve.no/api/v1/Observations?StationId=122.9.0&Parameter=1001&ResolutionTime=0&ReferenceTime=P2D/",{headers:{"X-API-Key":key,accept:"application/json"}}),o=j.data?.[0]?.observations||[],last=o.at(-1);return{station:"Gaulfoss",stationId:"122.9.0",current:last?.value??null,observedAt:last?.time??null,history:o.slice(-24).map(x=>({time:x.time,value:x.value}))}}
function summary(rows){const todayRows=rows.filter(x=>x.date===today),weights=todayRows.map(x=>x.weight).filter(Boolean);return{count:todayRows.length,averageWeight:weights.length?weights.reduce((a,b)=>a+b,0)/weights.length:null}}
let old={};try{old=JSON.parse(await readFile("data/live.json","utf8"))}catch{}
const borten=await beatId("Borten/Losen Fiskesameie");const jobs=await Promise.allSettled([nve(),catches(1861,"Nedre Løberg"),catches(2594,"Midtlyng / Høiseth"),catches(borten,"Borten/Losen Fiskesameie"),catches(2631,"Valdøyan/Valdum")]);
const [w,a,b,down,up]=jobs,all=[...(a.status==="fulfilled"?a.value:[]),...(b.status==="fulfilled"?b.value:[])].sort((x,y)=>new Date(y.dateTime)-new Date(x.dateTime));
const output={updatedAt:new Date().toISOString(),nve:w.status==="fulfilled"?w.value:old.nve||null,lastSevenDays:all.length?all.filter(x=>new Date(x.dateTime)>=cutoff).length:old.lastSevenDays??null,catches:all.length?all.slice(0,10):old.catches||[],nearby:{downstream:down.status==="fulfilled"?summary(down.value):old.nearby?.downstream||null,upstream:up.status==="fulfilled"?summary(up.value):old.nearby?.upstream||null},sources:{nve:w.status,elveguiden:a.status==="fulfilled"&&b.status==="fulfilled"?"fulfilled":"partial"}};
await mkdir("data",{recursive:true});await writeFile("data/live.json",JSON.stringify(output,null,2)+"\n");
